version: "3"

services:
  database:
    restart: "unless-stopped"
    image: "postgres:10"
    environment:
      POSTGRES_USER: "wsf"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
  application:
    restart: "unless-stopped"
    image: "node:8"
    command: "node ./usr/src/app/index"
    ports:
      - "8080:8080"
    volumes:
      - "./application/:/usr/src/app/"
      - "./node_modules/:/usr/src/node_modules/"

volumes:
  postgres:
